Made Draft and Global components
WildCodeSchool/2022-09-JS-Reims-project-2-legends pull request #13
Opened 2022-11-03 15:48 UTC by iturnmyscreenon

Draft component with (DraftPage/Loader/PlayerSelection) 
Global component with (Card/MiniCard)
// Modified Div into Section

2022-11-03 16:22 UTC, rocambille requested changes

2022-11-03 16:22 UTC, rocambille commented on frontend/src/components/Draft/DraftPage.jsx
> +  cardSelected: PropTypes.arrayOf(PropTypes.objectOf(PropTypes.shape))
cardSelected is not an array of object of shape, it's an array of shape. and in shape, you have to detail the properties. something like that :

    cardSelected: PropTypes.arrayOf(PropTypes.shape({
      foo: PropTypes.string.isRequired,
      bar: PropTypes.number.isRequired,
      subObject: PropTypes.shape({
        ...
      }),
      ...
    }),

2022-11-03 16:22 UTC, rocambille commented on frontend/src/components/Draft/PlayersSelection.jsx
> +        <h2 className="text-center h-[10%]">Opponent Deck</h2>
there is a title here

2022-11-03 16:22 UTC, rocambille commented on frontend/src/components/Draft/PlayersSelection.jsx
> +  cardSelected: PropTypes.arrayOf(PropTypes.objectOf(PropTypes.shape))
fix prop types definition

2022-11-03 16:22 UTC, rocambille commented on frontend/src/components/Global/Card.jsx
> +  ).isRequired,
that the correct way to declare prop types :)

2022-11-03 16:22 UTC, rocambille commented on frontend/src/components/Draft/DraftPage.jsx
> +  cardSelected: PropTypes.arrayOf(PropTypes.objectOf(PropTypes.shape))
good news, what you're looking for is :

    cardSelected: PropTypes.arrayOf(Card.propTypes)

(with the needed import)

2022-11-10 08:42 UTC, Justine-Merlin requested changes

2022-11-10 08:42 UTC, Justine-Merlin commented on frontend/src/components/Draft/PlayersSelection.jsx
> +        image: PropTypes.PropTypes.objectOf(
Same.

2022-11-10 08:42 UTC, Justine-Merlin commented on frontend/src/components/Draft/PlayersSelection.jsx
> +        powerstats: PropTypes.objectOf(
Same.

2022-11-10 08:42 UTC, Justine-Merlin commented on frontend/src/components/Draft/PlayersSelection.jsx
> +        image: PropTypes.PropTypes.objectOf(
Delete all others objectOf.

2022-11-10 11:30 UTC, merged