Made Deck component to refactor Minicard code
WildCodeSchool/2022-09-JS-Reims-project-2-legends pull request #19
Opened 2022-11-16 10:56 UTC by iturnmyscreenon

2022-11-16 11:38 UTC, rocambille requested changes

2022-11-16 15:25 UTC, iturnmyscreenon commented
As requested, i stored the propTypes shape in propTypes.js and replaced powerstats as strings

2022-11-16 15:57 UTC, rocambille requested changes

2022-11-16 15:57 UTC, rocambille commented on frontend/src/components/propTypes.js
> +});
try:

```js
const cardPropType = PropTypes.shape({
  id: PropTypes.number,
  name: PropTypes.string,
  powerstats: PropTypes.shape({
    intelligence: PropTypes.string,
    strength: PropTypes.string,
    speed: PropTypes.string,
    durability: PropTypes.string,
    power: PropTypes.string,
    combat: PropTypes.string,
  }),
  image: PropTypes.shape({ url: PropTypes.string }),
});

const cardArrayPropType = PropTypes.arrayOf(cardPropType);
```

2022-11-16 16:15 UTC, iturnmyscreenon commented on frontend/src/components/propTypes.js
> +});
Done.

2022-11-16 16:35 UTC, rocambille requested changes

2022-11-17 09:09 UTC, iturnmyscreenon commented
the import and export were fixed

2022-11-17 09:22 UTC, merged