gitignore add tailwind rules for ignore
WildCodeSchool/2022-09-JS-Reims-project-2-legends pull request #2
Opened 2022-10-20 15:15 UTC by Yhugzee

2022-10-20 15:26 UTC, rocambille requested changes

2022-10-20 15:26 UTC, rocambille commented on frontend/.gitignore
> +postcss.config.js
this should not be ignored :)

2022-10-20 15:26 UTC, rocambille commented on frontend/src/App.css
> +  height: 100vh;
prefer min-height

2022-10-20 15:26 UTC, rocambille commented on frontend/src/components/Menu.jsx
> +    <div>
div should not have titles, header do

2022-10-20 15:26 UTC, rocambille commented on frontend/src/pages/Home.jsx
> +    <header>
use header in Menu ;)

2022-10-23 14:02 UTC, Yhugzee commented on frontend/.gitignore
> +postcss.config.js
Okay ^^

2022-10-23 14:06 UTC, Yhugzee commented on frontend/src/App.css
> +  height: 100vh;
✅

2022-10-26 07:32 UTC, Yhugzee commented on frontend/src/components/Menu.jsx
> +    <div>
✅

2022-10-26 07:32 UTC, Yhugzee commented on frontend/src/pages/Home.jsx
> +    <header>
✅

2022-10-26 08:25 UTC, rocambille commented
conflicts to resolve

2022-10-26 13:40 UTC, merged